# Индексы и срезы

## Индекс элемента массива

Чтобы получить доступ к элементу массива, то необходимо вначале указать индекс внешнего измерения (оно будет первым по счету в выводе атрибута shape), а затем индекс внутреннего

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a[0]

array([1, 2, 3])

In [6]:
a[0][0]

1

In [7]:
a[1][1]

5

## Срез массива

In [8]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
b[1:6:2]

array([2, 4, 6])

In [10]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# 0 указывает на первую строку, диапазон :2 - на первые два столбца
c[0, :2]

array([1, 2])

In [12]:
# возьмем обе строки во втором столбце
c[:, 1]

array([2, 6])

In [13]:
c[::]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# выведем элемент в первой строке и первом столбце
c[0, 0]

1

In [15]:
# выведем элемент в последней строке и последнем столбце
c[-1, -1]

8

In [16]:
c[1, ::2] # Возьмем всю вторую строку [1] и каждый второй столбец [::2]

array([5, 7])

In [17]:
# -1 означает, что Питон сам рассчитает количество элементов в этом измерении
d = np.arange(16).reshape(4, 2, -1)
d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [18]:
d[2][1][0]

10

In [19]:
# выведем третью и четвертую матрицу [2:]
# и в них вторую строку [1] и все столбцы [:]
d[2:, 1, :]

array([[10, 11],
       [14, 15]])

In [20]:
# выведем первые две матрицы массива
d[:2]

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# выведем первые строки каждой матрицы
d[:, 0 , :]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])