# Операции с массивами

## Функция len()

In [1]:
import numpy as np

In [2]:
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [3]:
len(arr_3D) # две матрицы

2

In [4]:
len(arr_3D[0][0]) # длину внутреннего измерения, т.е. вектора из трех элементов (ось 1)

3

## Вхождение элемента в массив

In [5]:
3 in arr_3D

True

In [7]:
11 not in arr_3D

False

## Распаковка массива

In [8]:
a = np.arange(1, 28).reshape(3, 9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [9]:
x, y, z = a

In [10]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x, *y, z = a[0] # распакуем первый, последний и остальные элементы первой строки в отдельные переменные

In [12]:
print(x)
print(y)
print(z)

1
[2, 3, 4, 5, 6, 7, 8]
9


## Изменение элементов массива

In [13]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr_2D[0, 0] = 2 # Заменим первый элемент первой строки по его индексу
arr_2D

array([[2, 2, 3],
       [4, 5, 6]])

In [15]:
arr_2D[0] = 1 # Запишем значение 1 в первую строку
arr_2D

array([[1, 1, 1],
       [4, 5, 6]])

In [16]:
arr_2D[:,2] = 0 # Пусть третий столбец массива состоит из нулей
arr_2D

array([[1, 1, 0],
       [4, 5, 0]])

In [17]:
arr_2D[1,:] = 0 # Пусть вторая строка массива состоит из нулей
arr_2D

array([[1, 1, 0],
       [0, 0, 0]])

In [18]:
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [19]:
# при такой операции размер среза должен совпадать
# с количеством передаваемых значений
arr_3D[1, :, 1] = [0, 1] # Выберем второй столбец второй матрицы и заменим значения столбца 7 и 10 на 0 и 1
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  0,  8],
        [ 9,  1, 11]]])

In [20]:
arr_3D.fill(7) # Заменим все элементы массива на число семь 
arr_3D

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

## Сортировка массива и обратный порядок его элементов

## Функция np.sort()

In [21]:
a = np.array([[4, 8, 2], [2, 3, 1]])
a

array([[4, 8, 2],
       [2, 3, 1]])

In [23]:
np.sort(a) # По умолчанию сортировка идет с параметром axis = −1 (последняя ось)

array([[2, 4, 8],
       [1, 2, 3]])

In [24]:
np.sort(a, axis = 1)

array([[2, 4, 8],
       [1, 2, 3]])

In [25]:
np.sort(a, axis = 0)

array([[2, 3, 1],
       [4, 8, 2]])

In [27]:
np.sort(a, axis = None) # Параметр axis = None вначале возвращает одномерный массив, а затем сортирует его

array([1, 2, 2, 3, 4, 8])

## Обратный порядок элементов массива

In [28]:
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
# Обратный порядок элементов можно совмещать со срезами
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])[-3: 3: -1]

array([7, 6, 5, 4])

In [30]:
a = np.array([[4, 8, 2], [2, 3, 1], [1, 7, 2]])
a

array([[4, 8, 2],
       [2, 3, 1],
       [1, 7, 2]])

In [31]:
# такая запись аналогична параметру axis = (0, 1)
a[::-1, ::-1]

array([[2, 7, 1],
       [1, 3, 2],
       [2, 8, 4]])

In [32]:
# обратный порядок по внешнему (axis = 0)
a[::-1]

array([[1, 7, 2],
       [2, 3, 1],
       [4, 8, 2]])

In [33]:
# и внутреннему измерению (axis = 1)
a[:, ::-1]

array([[2, 8, 4],
       [1, 3, 2],
       [2, 7, 1]])

In [34]:
# то же самое, что axis = (0, 1) 
np.flip(a) # обратный порядок можно задать через функцию np.flip()

array([[2, 7, 1],
       [1, 3, 2],
       [2, 8, 4]])

In [35]:
# внешнее измерение
np.flip(a, axis = 0)

array([[1, 7, 2],
       [2, 3, 1],
       [4, 8, 2]])

In [36]:
# внутреннее измерение
np.flip(a, axis = 1)

array([[2, 8, 4],
       [1, 3, 2],
       [2, 7, 1]])

## Сортировка в убывающем порядке

In [37]:
# возьмем простой одномерный массив
a = np.array([4, 2, 6, 1, 7, 3, 5])

In [38]:
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [39]:
# исходный массив не изменился
a

array([4, 2, 6, 1, 7, 3, 5])

In [40]:
# здесь нужно сначала задать обратный порядок, а потом отсортировать
a[::-1].sort()

In [41]:
a

array([7, 6, 5, 4, 3, 2, 1])

## Изменение размерности

## Метод .reshape()

In [42]:
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [43]:
# в нем 12 элементов
arr_3D.size

12

In [44]:
# С помощью метода .reshape() мы можем изменить количество измерений
# при этом важно, чтобы общее количество элементов было тем же
arr_2D = arr_3D.reshape(2, 6) # превратить этот массив в матрицу с размерностью 2 x 6
arr_2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## Функция np.resize() и метод .resize()

если мы хотим не только задать другую размерность, но и изменить общее количество элементов, то мы можем воспользоваться функцией np.resize() и методом .resize()

In [48]:
# функция np.resize() позволяет не сохранять прежнее количество элементов
# существующие элементы копируются в новые ячейки
np.resize(arr_2D, (3, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

Перед тем как воспользоваться методом .resize() нам необходимо создать копию массива arr_2D. Все дело в том, что переменная arr_2D ссылается на другой массив (в частности, на трехмерный массив arr_3D), а метод .resize() может работать только с исходным массивом

In [49]:
arr_2D_copy = arr_2D.copy()

Метод .resize() также создаст отдельную копию, изменит размерность и заполнит пропуски нулями.

In [50]:
arr_2D_copy.resize(4, 6)
arr_2D_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

## Методы .flatten() и .ravel()

Метод .flatten() переводит («вытягивает») массив в одно измерение и создает копию исходного массива (как метод .copy())

In [51]:
arr_3D.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Метод .ravel() делает то же самое, но не создает копию исходного массива и за счет этого быстрее, чем .flatten()

In [52]:
arr_3D.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## np.newaxis

Объект np.newaxis добавляет измерение в уже существующем массиве

In [53]:
# создадим одномерный массив
a = np.array([1, 2, 3])
a.shape

(3,)

In [54]:
# добавить в этот массив новое первое измерение и, таким образом, сделать существующее измерение вторым
b = a[np.newaxis, :]
 
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [55]:
# добавить новое второе измерение, а существующее измерение оставить первым
c = a[:, np.newaxis]
 
print(c)
print(c.shape)

[[1]
 [2]
 [3]]
(3, 1)


## Функция np.expand_dims()

Функция np.expand_dims() добавляет измерение, указанное в параметре axis

In [56]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [58]:
# Добавим внешнее измерение
np.expand_dims(a, axis = 0)

array([[[1, 2],
        [3, 4]]])

In [60]:
# добавим измерение «по середине»
np.expand_dims(a, axis = 1)

array([[[1, 2]],

       [[3, 4]]])

In [61]:
# внутреннее измерение
np.expand_dims(a, axis = 2)

array([[[1],
        [2]],

       [[3],
        [4]]])

## Функция np.squeeze()

In [62]:
arr_4D = np.arange(9).reshape(1, 3, 3, 1)
arr_4D

array([[[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]],

        [[6],
         [7],
         [8]]]])

In [63]:
np.squeeze(arr_4D) # Новый массив имеет только два измерения

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
np.squeeze(arr_4D).shape

(3, 3)

## Объединение массивов

## Функция np.concatenate()

In [65]:
# есть два квардратных массива a и b размерностью 2 x 2
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [66]:
b = np.arange(4, 8).reshape(2, 2)
b

array([[4, 5],
       [6, 7]])

In [67]:
# Объединим массивы вдоль оси 0 без добавления нового измерения
np.concatenate((a, b), axis = 0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [68]:
np.concatenate((a, b), axis = 1)

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

## Функция np.stack()

Отличие функции np.stack() от np.concatenate() в том, что при объединении массивов мы добавляем новое измерение (новую ось)

In [69]:
# при axis = 0 мы просто добавляем внешнее измерение
np.stack((a, b), axis = 0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
# при axis = 1 мы объединяем первые и вторые строки двух массивов
np.stack((a, b), axis = 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [71]:
# при axis = 2 объединяются элементы с одинаковыми индексами
np.stack((a, b), axis = 2)

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

## Фильтр (маска) массива

Задача фильтрации массива (или как еще говорят создания маски массива) встречается довольно часто. К примеру, предположим, что мы собрали показания прибора, однако из-за ошибки датчика часть из них оказалась некорректной, и для последующего анализа эти значения нужно удалить.

## Логическая маска (Boolean mask)

In [72]:
a = np.array([5, 7, -3, 4, 2, -4]) # хотим удалить из него отрицательные значения

Для того чтобы создать фильтр массива достаточно указать критерий отбора. На выходе мы получим массив из логических значений True и False, в котором нежелательные значения будут помечены как False

In [73]:
a > 0

array([ True,  True, False,  True,  True, False])

In [74]:
# Применим маску к исходному массиву
# останутся только те значения, которые в маске помечены как True
a[a > 0]

array([5, 7, 4, 2])

In [75]:
a[a < 0] = 0 # oтфильтрованные значения можно заполнить, например, нулями
a

array([5, 7, 0, 4, 2, 0])

## Masked array

Альтернативный способ фильтрации массива Numpy предполагает использование модуля ma (masked array)

In [76]:
# импортируем модуль ma
import numpy.ma as ma
 
# вновь воспользуемся массивом с отрицательными числами
a = np.array([5, 7, -3, 4, 2, -4])

В отличие от описанного выше логического фильтра, в masked array опускаются элементы, помеченные как 1 или True

In [77]:
# функции masked_array мы передаем сам массив и его маску с 0 или 1
ma.masked_array(a, mask = [0, 0, 1, 0, 0, 1])

masked_array(data=[5, 7, --, 4, 2, --],
             mask=[False, False,  True, False, False,  True],
       fill_value=999999)

In [78]:
# можно также передать значения False или True
ma.masked_array(a, mask = [False, False, True, False, False, True])

masked_array(data=[5, 7, --, 4, 2, --],
             mask=[False, False,  True, False, False,  True],
       fill_value=999999)

Кроме того, для некоторых логических условий есть отдельные функции. Например, мы можем опустить все элементы меньше определенного значения

In [79]:
# в данном случае меньше 0
ma.masked_less(a, 0)

masked_array(data=[5, 7, --, 4, 2, --],
             mask=[False, False,  True, False, False,  True],
       fill_value=999999)

Рассмотрим еще одну возможность модуля ma. Возьмем массив, в котором есть пропущенные значения (NaN, Not a Number) и значение бесконечности (inf, infinity)

In [80]:
b = np.array([5, 7, np.nan, 4, 2, np.inf])

In [81]:
b.sum()

nan

Для решения этой проблемы мы можем применить функцию masked_invalid(). Она автоматически отфильтровывает пропущенные значения и значения бесконечности.

In [82]:
b_masked = ma.masked_invalid(b)
b_masked

masked_array(data=[5.0, 7.0, --, 4.0, 2.0, --],
             mask=[False, False,  True, False, False,  True],
       fill_value=1e+20)

In [83]:
b_masked.sum()

18.0

In [84]:
# с помощью метода .filled() мы можем заполнить образовавшиеся пропуски
# использование среднего значения часто является более предпочтительным
# способом заполнения пропусков
b_masked.filled(b_masked.mean())

array([5. , 7. , 4.5, 4. , 2. , 4.5])