# Оси массива

## Массив 2D

In [1]:
import numpy as np

In [2]:
arr_2D = np.array([[1, 2], [3, 4]])
arr_2D

array([[1, 2],
       [3, 4]])

In [3]:
np.sum(arr_2D, axis = 0) # сумму по столбцам (вдоль оси 0)

array([4, 6])

In [4]:
np.sum(arr_2D, axis = 1) # сумму по строкам (вдоль оси 1)

array([3, 7])

In [5]:
# Сложение вдоль обеих осей (axis = (0, 1))
np.sum(arr_2D, axis = (0, 1)) # 4 + 6

10

In [6]:
np.sum(arr_2D) # по умолчанию axis = None

10

## Отрицательные значения в параметре axis

In [7]:
np.sum(arr_2D, axis = -1) # соответствует последней по счету оси

array([3, 7])

In [8]:
np.sum(arr_2D, axis = -2) # Сложение вдоль оси 0

array([4, 6])

## Массив 3D

In [10]:
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [11]:
np.sum(arr_3D, axis = 0)

array([[ 6,  8, 10],
       [12, 14, 16]])

Если использовать индексы массива, то поэлементное сложение вдоль оси 0 можно реализовать следующим образом.

In [12]:
# возьмем первую матрицу
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# возьмем вторую матрицу
arr_3D[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
# и поэлементно сложим их
arr_3D[0] + arr_3D[1]

array([[ 6,  8, 10],
       [12, 14, 16]])

Эту же задачу можно решить с помощью цикла for. Вначале нужно создать нулевую матрицу, размерность которой будет соответствовать желаемому результату сложения вдоль оси 0.

In [15]:
# создадим нулевую матрицу размером 2 x 3
total = np.zeros((2, 3))

Теперь создадим цикл for с двумя итерациями (потому что мы складываем две матрицы внутри трехмерного массива) через функцию range() с параметром 2

In [16]:
for i in range(2):
  total += arr_3D[i]

Внутри цикла мы на первой итерации (i равно 0) запишем в нулевой массив нашу первую матрицу, а на второй итерации (i равно 1) поэлементно прибавим вторую. Переменная i в данном случае стала индексом для массива arr_3D

In [17]:
total

array([[ 6.,  8., 10.],
       [12., 14., 16.]])

In [19]:
# применим np.sum()
np.sum(arr_3D, axis = 1) # Сложение вдоль второй оси

array([[ 3,  5,  7],
       [15, 17, 19]])

In [20]:
# сложим столбцы первой
arr_3D[0][0] + arr_3D[0][1]

array([3, 5, 7])

In [21]:
# и второй матрицы
arr_3D[1][0] + arr_3D[1][1]

array([15, 17, 19])

In [22]:

# создадим нулевую матрицу 2 x 3
total = np.zeros((2, 3))
 
# вначале пройдемся по матрицам
for i in range(2):
 
  # затем по строкам каждой матрицы
  for j in range(2):
 
    # и в первую строку total запишем сумму столбцов первой матрицы arr_3D,
    # а во вторую - сумму столбцов второй матрицы
    total[i] += arr_3D[i][j]
 
total

array([[ 3.,  5.,  7.],
       [15., 17., 19.]])

In [23]:
# применим np.sum()
np.sum(arr_3D, axis = 2) # Сложение вдоль третьей оси (axis = 2)

array([[ 3, 12],
       [21, 30]])

Сложение вдоль оси 2 предполагает, что мы складываем строки каждой матрицы

In [24]:
# создадим нулевой массив 2 x 2 для записи результатов
total = np.zeros((2, 2))
 
# пройдемся по матрицам
for i in range(2):
 
  # по строкам матрицы
  for j in range(2):
 
    # и по столбцам
    for k in arr_3D[i][j]:
 
      # индексы i, j запишут результат сложения элементов строк k
      # в квадратную матрицу 2 x 2
      total[i][j] += k
 
total

array([[ 3., 12.],
       [21., 30.]])

## Сложение вдоль первой и второй осей (axis = (0, 1))

In [25]:
# применим функцию np.sum()
np.sum(arr_3D, axis = (0, 1))

array([18, 22, 26])

In [26]:
# произведем сложение по оси 0
total_0 = np.zeros((2, 3))
 
for i in range(2):
  total_0 += arr_3D[i]
 
total_0

array([[ 6.,  8., 10.],
       [12., 14., 16.]])

In [27]:
# произведем сложение по оси 1
total_1 = np.zeros(3)
 
for j in range(2):
  total_1 += total_0[j]
 
total_1

array([18., 22., 26.])

## Сложение вдоль всех трех осей (axis = (0, 1, 2))

In [28]:
np.sum(arr_3D, axis = (0, 1, 2))

66

In [29]:
np.sum(arr_3D)

66

In [30]:
total = 0
 
# в трех вложенных циклах мы пройдемся по всем элементам массива
for i in range(2):
  for j in range(2):
    for k in range(3):
 
      # и запишем сумму этих элементов в переменную total
      total += arr_3D[i][j][k]
 
total

66