# Задания

Создайте двумерный массив 2 x 8 с помощью np.arange() и np.reshape(). Выведите основные атрибуты массива.

In [1]:
import numpy as np

In [5]:
arr = np.arange(16).reshape(2, 8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [6]:
arr.size

16

In [7]:
arr.shape

(2, 8)

Выведите последний элемент первой строки, а затем третий по счету столбец.

In [8]:
arr[0][-1]

7

In [10]:
arr[:,2]

array([ 2, 10])

Найдите средние значения вдоль последней оси массива.

Подсказка: используйте метод .mean()

In [11]:
arr[1].mean()

11.5

 Замените первые два элемента второй строки и весь последний столбец на значение 3.

In [29]:
arr2 = np.arange(16).reshape(2, 8)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [32]:
arr2[1,:2] = 3

In [33]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 3,  3, 10, 11, 12, 13, 14, 15]])

In [35]:
arr2[:,-1] = 3

In [36]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  3],
       [ 3,  3, 10, 11, 12, 13, 14,  3]])

Отсортируйте первую строку массива от большего к меньшему значению.

In [39]:
np.sort(arr2)

array([[ 0,  1,  2,  3,  3,  4,  5,  6],
       [ 3,  3,  3, 10, 11, 12, 13, 14]])

In [54]:
arr2[0].sort()
arr2

array([[ 0,  1,  2,  3,  3,  4,  5,  6],
       [ 3,  3,  3, 10, 11, 12, 13, 14]])

In [55]:
ar = arr2[0]
ar

array([0, 1, 2, 3, 3, 4, 5, 6])

In [56]:
ar[::-1].sort()

In [57]:
ar

array([6, 5, 4, 3, 3, 2, 1, 0])

Преобразуйте массив в квадратную матрицу 4 x 4.

In [69]:
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
arr_2D = arr4.reshape(4, 4)
arr_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Используйте Boolean mask или masked array и опустите значения, которые больше шести.

In [76]:
import numpy.ma as ma
# подсказка: маска двумерного массива - это тоже массив 2D
c = np.array([[0, 1], [2, 3]])

# оставим только те значения, которые больше нуля
ma.masked_array(c, mask = [[1, 0], [0, 0]])

masked_array(
  data=[[--, 1],
        [2, 3]],
  mask=[[ True, False],
        [False, False]],
  fill_value=999999)

In [78]:
w = np.array([10, 5, 7, 1, 3, 9, 12, 2, 4])
ma.masked_array(w, mask = [True, False, True, False, False, True, True, False, False])

masked_array(data=[--, 5, --, 1, 3, --, --, 2, 4],
             mask=[ True, False,  True, False, False,  True,  True, False,
                   False],
       fill_value=999999)