# Индексация массивов в NumPy

как можно получить отдельные элементы или набор элементов из массива.

In [1]:
import numpy as np

In [2]:
# Создаём некоторый массив
arr = np.arange(0,11)

In [3]:
# Отображаем его
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Индексация с помощью скобок

Самый простой способ выбрать один или несколько элементов из массива выглядит так же, как и для списков python:

In [4]:
# Получить значение по указанному индексу
arr[8]

8

In [5]:
# Получить диапазон значений
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting (широковещание, вещание, трансляция, бродкастинг)

В отличие от списков Python, массивы NumPy позволяют применить какую-нибудь операцию сразу для всех элементов массива. Например, если вы хотите для списка заменить первые 5 элементов на другое значение, то Вы должны указать новый список из 5 значений - так, чтобы новый список был такой же размерности. Для массивов NumPy это необязательно - Вы можете указать одно значение сразу для большого количества элементов:

In [6]:
# Присваиваем значение для диапазона индекса (Broadcasting)
arr[0:5]=100

# Отображаем массив
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Сбрасываем массив обратно
arr = np.arange(0,11)

# Отображаем весь массив
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Важное замечание по поводу срезов (slices)
slice_of_arr = arr[0:6]

# Отображаем только срез
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
# Вносим изменения в срез
slice_of_arr[:]=99

# Снова отображаем срез
slice_of_arr

array([99, 99, 99, 99, 99, 99])

эти изменения были внесены и в исходный массив!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Данные не копируются - это просто ссылка на исходный массив! Такой подход позволяет экономить память!

In [12]:
# Чтобы сделать копию, это нужно указать явно
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Индексация двумерных массивов (матриц)

Общий формат: arr_2d[row][col] или arr_2d[row,col]. Лучше использовать вариант с запятой, так более наглядно.

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Отображаем массив
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
# Индексация строки
arr_2d[1]

array([20, 25, 30])

In [15]:
# Формат arr_2d[row][col] или arr_2d[row,col]

# Получаем отдельный элемент матрицы
arr_2d[1][0]

20

In [16]:
# Получаем отдельный элемент матрицы
arr_2d[1,0]

20

In [17]:
# Двумерный массив - срезы

# Форма (2,2) от верхнего правого угла
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
# Нижний ряд
arr_2d[2]

array([35, 40, 45])

In [19]:
# Нижний ряд
arr_2d[2,:]

array([35, 40, 45])

## Выбор элементов по условию (Conditional Selection

In [21]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr > 4

In [24]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])