___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Операции NumPy

## Арифметика

Вы можете выполнять арифметику "массив и массив" или "скаляр и массив". Рассмотрим несколько примеров:

In [3]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Такое деление приведёт к возникновению предупреждения (Warning) о делении на ноль. Это не ошибка (error)!
# В том месте, где произошло деление на ноль, будет записано значение nan (not-a-number)
arr/arr

C:\Users\Ирина\AppData\Local\Temp\ipykernel_10696\2230634677.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# То же самое - предупреждение warning (не ошибка error) - возникает в случае бесконечности. 
# В этом случае записывается значение inf (infinity)
1/arr

C:\Users\Ирина\AppData\Local\Temp\ipykernel_10696\1688146030.py:3: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Универсальные функции для массивов (Universal Array Functions)

В NumPy есть много [универсальных функций для массивов](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), <em>ufuncs</em>, которые по сути представляют собой математические операции, которые можно применить сразу ко всем элементам массива.<br>Рассмотрим наиболее часто встречающиеся функции:

In [10]:
# Квадратный корень (sqrt = square root)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
# Экспонента - число e в степени (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [12]:
# Тригонометрические функции, например синус
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
# Натуральный логарифм
np.log(arr)

C:\Users\Ирина\AppData\Local\Temp\ipykernel_10696\3484349618.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Результаты функций агрегации для массивов

NumPy также позволяет найти результаты функций агрегации, такие как <em>sum</em>, <em>mean</em> и <em>max</em>. Их можно вызвать как методы массива.

In [14]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.sum()

45

In [16]:
arr.mean()

4.5

In [17]:
arr.max()

9

<strong>Другие агрегатные статистики:</strong>
<pre>

1) минимальное значение - arr.min() возвращает 0                   

2) дисперсия           - arr.var() возвращает 8.25   
  (var = variance)

3) среднеквадратическое отклонение - arr.std() возвращает 2.8722813232690143   
  (std - standard deviation)
</pre>

## Использование горизонтальной и вертикальной осей (Axis)
При работе с двумерными массивами - матрицами - мы работаем со строками (rows) и колонками (columns). Это станет очень важным, когда мы далее будем работать с pandas. В терминах массивов, ось 0 (ноль) это вертикальная ось (строки), а ось 1 это горизонтальная ось (колонки). Эти значения (0,1) следуют в том же порядке, в котором значения перечислены в атрибуте <tt>arr.shape</tt>.

Давайте посмотрим, как можно вычислить агрегатные статистики (sum, min, max и т.д.) с использованием осей.

In [18]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

Указывая <tt>axis=0</tt>, мы получаем массив с суммами вдоль вертикальной оси, то есть: <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

In [20]:
arr_2d.shape

(3, 4)

Здесь мы видим, что <tt>arr_2d</tt> содержит 3 строки и 4 колонки.

Применяя <tt>arr_2d.sum(axis=0)</tt>, сначала суммируются все первые элементы в каждой строке, затем все вторые элементы, и так далее.

А теперь задание - как Вы думаете, что вернёт <tt>arr_2d.sum(axis=1)</tt> ?

In [21]:
# ПРЕЖДЕ ЧЕМ ЗАПУСКАТЬ ЭТУ ЯЧЕЙКУ, ПОДУМАЙТЕ, ЧТО ВЕРНЁТ ЭТА КОМАНДА!
arr_2d.sum(axis=1)

array([10, 26, 42])

# Отличная работа!

Пока это всё, что нам нужно знать на данный момент!